### ISSUE TITLE
Unable to run SD creation process from online scripts

### ISSUE THREAD

**Issue by ubidefeo** [WebReflection/archibold.io#9]
I keep getting failure to execute `bash <(curl -s https://archibold.io/benja/prepare)`

```
/dev/fd/14: line 37: echoWithLogo: command not found
/dev/fd/14: line 39: diskSize: command not found
/dev/fd/14: line 41: [: : integer expression expected
/dev/fd/14: line 55: echomd: command not found
/dev/fd/14: line 56: echomd: command not found
(23) Failed writing body
```

I have fixed this by going through every `bash <()` call and downloading files locally, later replacing that call with `source "./filename.dms"`

not sure where the issue stands, to be honest, but it must be how commands are setup when remote scripts are executed/included.
would take me longer to investigate than what it took me to download all the scripts and run them locally :)

**Comment by ubidefeo** [comment]
for some reason I ended up posting issues to the wrong repo.
closing.

**Comment by WebReflection** [comment]
I never had any issue with this approach, and the whole point of this project is to be remote oriented. Which platform / OS are giving you troubles? If that's OSX/macOS, have you updated bash to run latest version? AFAIK it ships with version 3, instead of 5, but `brew install bash` should solved that.

Maybe worth underlying this in the README/documentation?

**Comment by ubidefeo** [comment]
@WebReflection as you pointed out "the Mac is an idiot".
`brew install bash` did the trick and solved it for me
